# Use Node.js 20 base image
FROM node:20

# Set working directory inside container
WORKDIR /app
#
## Copy package.json and lock file first (better for caching)
#COPY package*.json tsconfig.json ./
#
## Install dependencies
#RUN npm install
#
## Copy the rest of the source code
#COPY . .

## Build TypeScript into dist/
#RUN npm run build
#
## Expose the port (must match your Express app, default 8080)
#EXPOSE 8080

